version: '3.8'

services:
  backend:
    image: my-backend:latest
    ports: ["8080:8080"]
    networks: ["app-network"]
    environment: ["DB_HOST=db", "DB_USER=root", "DB_PASSWORD=rootpass", "DB_NAME=docker_demo"]
    depends_on: [db]
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    ports: ["3306:3306"]
    networks: ["app-network"]
    environment: ["MYSQL_ROOT_PASSWORD=rootpass", "MYSQL_DATABASE=docker_demo"]
    deploy:
      placement:
        constraints: [node.role == manager]

  frontend:
    image: my-frontend:latest
    ports: ["3000:3000"]
    networks: ["app-network"]
    deploy:
      placement:
        constraints: [node.role == worker]

networks:
  app-network:
    driver: overlay
