version: '3.7'

services:
  backend:
    build: ./backend               # Build the image using Dockerfile from ./backend directory
    ports:
      - "8080:8080"                # Map container port 5000 to host port 5000
    networks:
      - app-network               # Connect to custom bridge network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]  # Health check hitting backend API
      interval: 30s
      timeout: 10s
      retries: 3
  frontend:
    build: ./frontend
    ports:
     - "3000:80"
    networks:
     - app-network
    depends_on:
     - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval;: 30s
      timeout: 10s
      retries: 3
networks:
  app-network:
    driver: bridge                # Define custom bridge network
