version: '3.7' 

services:
  # ------------------- Backend Service -------------------
  backend:
    build: ./backend  
    ports:
      - "8080:8080"     
    networks:
      - app-network     
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpass
      - DB_NAME=docker_demo
    depends_on:
      - db             
    healthcheck:       
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]  
      interval: 30s    
      timeout: 10s      
      retries: 3        
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # ------------------- Frontend Service -------------------
  frontend:
    build: ./frontend  
    ports:
      - "80:80"        
    networks:
      - app-network    
    depends_on:
      - backend       
    healthcheck:        
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]   
      interval: 30s    
      timeout: 10s    
      retries: 3        
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # ------------------- Auth Service -------------------
  auth:
    build: ./auth       
    ports:
      - "6000:6000"     
    networks:
      - app-network     
    healthcheck:        
      test: ["CMD", "curl", "-f", "http://localhost:6000/health"]  
      interval: 30s    
      timeout: 10s      
      retries: 3        
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  # ------------------- MySQL Database Service -------------------
  db:                 
    image: mysql:8.0   
    ports:            
      - "3306:3306"   
    networks:
      - app-network     
    environment:      
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=docker_demo
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  # .................... phpmyadmin service -----------------------    
  phpmyadmin:   
    image: phpmyadmin/phpmyadmin   
    restart: always
    ports:
      - "8081:80"      
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=rootpass
    depends_on:
      - db
    networks:
      - app-network
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
# ------------------- Custom Docker Network -------------------
networks:
  app-network:
    driver: bridge     

# ------------------- Persistent Volume -------------------
volumes:
  dbdata:
