 
name: Backend Service CI

on:
  push:
    paths:
      - 'backend/**'                    
      - '.github/workflows/backend.yml' 
  pull_request:
    paths:
      - 'backend/**'                    
      - '.github/workflows/backend.yml' 
  workflow_dispatch:                    

jobs:
  backend:
    runs-on: ubuntu-latest             

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          # Uninstall conflicting containerd packages
          sudo apt-get remove -y containerd containerd.io
          
          # Update package list
          sudo apt-get update

          # Install Docker dependencies
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release

          # Add Docker's official GPG key
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

          # Set up the stable Docker repository
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          # Install Docker Engine and Docker Compose
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          
          # Install Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          
          # Verify installation
          docker --version
          docker-compose --version

      - name: Build and start backend service with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build backend

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend service to be ready..."
          sleep 30  # Adjust the sleep time based on expected startup time

      - name: Check backend service health
        run: |
          echo "Testing backend service at http://localhost:8080"
          curl -f http://localhost:8080/health || echo "Backend service failed health check!"

      - name: Get backend service logs
        run: |
          echo "Fetching backend service logs"
          docker-compose logs backend

      - name: Get MySQL DB logs
        run: |
          echo "Fetching MySQL DB logs"
          docker-compose logs db

      - name: Check if MySQL service is accessible
        run: |
          echo "Checking if MySQL DB is accessible"
          docker-compose exec db mysqladmin ping -h localhost || echo "MySQL DB is not accessible!"

      - name: Run backend tests
        run: |
          echo "Running backend tests inside backend container"
          docker-compose exec -T backend npm test  # Ensure tests run inside the backend container

      - name: Shut down the Docker containers
        run: |
          docker-compose down
