# ----------------------------------------------------------
# GitHub Actions Workflow: Backend Service CI
# ----------------------------------------------------------

# 👇 Workflow name shown in GitHub Actions UI
name: Backend Service CI

# 👇 Trigger events
on:
  push:
    paths:
      - 'backend/**'                     # Trigger when backend files change
      - '.github/workflows/backend.yml' # Trigger when this workflow file changes
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  workflow_dispatch:                    # Allow manual workflow trigger

# 👇 Define job(s) to run
jobs:
  backend-service-ci:
    runs-on: ubuntu-latest              # Use latest Ubuntu runner

    services:
      docker:
        image: docker:24.0.6            # Use Docker service container
        options: --privileged

    steps:
      # ------------------- Checkout the Code -------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # ------------------- Set up Python (if applicable for backend tests) -------------------
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # ------------------- Install Dependencies -------------------
      - name: Install Python dependencies
        run: |
          cd backend/app
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ------------------- Build Docker Image -------------------
      - name: Build Backend Docker image
        run: |
          docker build -t backend-service ./backend

      # ------------------- Run Health Check Test -------------------
      - name: Test Backend container health
        run: |
          docker run -d --name backend-test -p 8080:8080 backend-service
          sleep 5
          curl --fail http://localhost:8080/health

      # ------------------- Cleanup -------------------
      - name: Cleanup containers
        run: docker rm -f backend-test || true
