name: Backend CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and start backend service with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build backend  # Only build and start the backend service

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend service to be ready..."
          sleep 30  # Adjust the sleep time based on expected startup time

      - name: Check backend service health
        run: |
          echo "Testing backend service at http://localhost:8080"
          curl -f http://localhost:8080/health || echo "Backend service failed health check!"  # Check health endpoint

      - name: Get backend service logs
        run: |
          echo "Fetching backend service logs"
          docker-compose logs backend  # Get logs for backend service

      - name: Check MySQL DB logs
        run: |
          echo "Fetching MySQL DB logs"
          docker-compose logs db  # Get logs for MySQL service

      - name: Check if MySQL service is accessible
        run: |
          echo "Checking if MySQL DB is accessible"
          docker-compose exec db mysqladmin ping -h localhost || echo "MySQL DB is not accessible!"  # MySQL ping check

      - name: Run backend tests (Optional)
        run: |
          echo "Running backend tests"
          # Add your backend testing commands here, e.g., unit tests or integration tests
          npm test

      - name: Shut down the Docker containers
        run: |
          docker-compose down  # Shut down all containers after testing
