# ------------------- Name of the GitHub Actions Workflow -------------------
name: Backend Service CI

# ------------------- Trigger Conditions -------------------
on:
  push:
    branches: [ main ]                 # Trigger workflow on push to 'main' branch
    paths:
      - 'backend/**'                   # Trigger only if files inside 'backend' directory are modified
  pull_request:
    branches: [ main ]                 # Trigger on pull requests targeting 'main' branch
    paths:
      - 'backend/**'                   # Trigger only if PR includes changes in 'backend' directory
  workflow_dispatch:                   # Allow manual trigger from GitHub UI

# ------------------- Define Jobs -------------------
jobs:
  build-and-run:
    runs-on: ubuntu-latest             # Use the latest Ubuntu runner

    steps:
      # ------------------- Checkout the Code -------------------
      - name: Checkout code
        uses: actions/checkout@v3

      # ------------------- Set up Docker Buildx -------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ------------------- Build and Start Services -------------------
      - name: Docker Compose Up
        run: |
          docker compose up -d --build

      # ------------------- Wait for Services to Initialize -------------------
      - name: Wait for services to be healthy
        run: |
          echo "Waiting 30 seconds for services to initialize..."
          sleep 30

      # ------------------- Health Check Test -------------------
      - name: Test backend service
        run: |
          echo "Testing backend service at http://localhost:8080"
          curl -f http://localhost:8080 || (echo "Service test failed!" && exit 1)

      # ------------------- Check Running Containers -------------------
      - name: Check running containers
        run: docker ps -a

      # ------------------- Cleanup -------------------
      - name: Clean up
        if: always()
        run: docker compose down --volumes --remove-orphans
