name: Docker Stack Local Test

on:
  push:
    paths:
      - '**/*.yml'
      - '**/Dockerfile'
      - '**/*.js'
      - '**/*.py'
      - '**/*.sql'
      - '**/package.json'
      - '**/requirements.txt'
  pull_request:

jobs:
  docker-stack-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Initialize Docker Swarm
        run: |
          docker swarm init

      - name: Create overlay network
        run: |
          docker network create --driver overlay --attachable app-network || true

      - name: Build and Deploy Docker Stack
        run: |
          docker stack deploy -c docker-stack.yml mystack
          echo "Waiting 30 seconds for services to stabilize..."
          sleep 30
          docker service ls
          docker stack ps mystack

      - name: Healthcheck Status
        run: |
          docker service ls
          echo "Checking running containers:"
          docker ps -a

      - name: Tear Down Stack
        if: always()
        run: |
          docker stack rm mystack
          sleep 10
          docker swarm leave --force
