name: Frontend Service CI

on:
  push:
    paths:
      - 'frontend/**'                   
      - '.github/workflows/frontend.yml' 
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  workflow_dispatch:                   

jobs:
  frontend-service-ci:
    runs-on: ubuntu-latest              

    services:
      docker:
        image: docker:24.0.6          
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Frontend Docker image
        run: |
          docker build -t frontend-service ./frontend

      - name: Test Frontend container health
        run: |
          docker run -d --name frontend-test -p 80:80 frontend-service
          sleep 5
          curl --fail http://localhost:80

      - name: Cleanup containers
        run: docker rm -f frontend-test || true
