# Name of the GitHub Actions workflow
name: Docker Compose CI - Frontend Only

# Trigger workflow only on frontend changes
on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Compose Up
        run: |
          docker compose up -d --build

      - name: Wait for services to be healthy
        run: |
          echo "Waiting 30 seconds for services to initialize..."
          sleep 30

      - name: Test frontend service
        run: |
          echo "Testing frontend service at http://localhost:80"
          curl -f http://localhost:80 || (echo "Service test failed!" && exit 1)

      - name: Check running containers
        run: docker ps -a

      - name: Clean up
        if: always()
        run: docker compose down --volumes --remove-orphans
