# Name of the GitHub Actions workflow
name: Docker Compose CI - frontend Only

# Trigger this workflow only on push or pull request events on the 'main' branch,
# and only if changes are made in the 'backend/' directory
on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-run:
    # Define the environment where this job will run
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional but helpful for better build capabilities)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build and run containers using Docker Compose
      - name: Docker Compose Up
        run: |
          echo "Checking Docker Compose version"
          docker compose --version
          
          echo "Building and starting services"
          docker compose up -d --build

      # Step 4: Wait for services to be healthy (adjust time if needed)
      - name: Wait for services to be healthy
        run: |
          echo "Waiting 30 seconds for services to initialize..."
          sleep 30

      # Step 5: Test the main service endpoint using curl
      - name: Test service endpoint
        run: |
          echo "Testing service at http://localhost:80"
          curl -f http://localhost:80 || (echo "Service test failed!" && exit 1)

      # Step 6: Show running containers (for verification/debugging)
      - name: Check running containers
        run: docker ps -a

      # Step 7: Clean up everything - stop containers, remove volumes/networks
      - name: Clean up
        if: always()   # Ensures this runs even if previous steps fail
        run: |
          echo "Cleaning up Docker containers and networks..."
          docker compose down --volumes --remove-orphans
