name: Compose Logs Collection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  collect-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Docker and Docker Compose Versions
        run: |
          docker --version
          docker compose version

      - name: Start Docker Compose Services
        run: docker compose up -d --build

      - name: Wait for Services to Initialize
        run: |
          docker compose ps
          sleep 30

      - name: Run Health Checks
        run: |
          docker compose exec backend curl -f http://localhost:8080/health || echo "Backend health check failed"
          docker compose exec frontend curl -f http://localhost:80/health || echo "Frontend health check failed"
          docker compose exec auth curl -f http://localhost:6000/health || echo "Auth health check failed"
          curl -f http://localhost:8081 || echo "phpMyAdmin health check might take time"

      - name: Collect Logs from Containers
        run: |
          mkdir -p docker-logs
          docker compose logs backend > docker-logs/backend.log
          docker compose logs frontend > docker-logs/frontend.log
          docker compose logs auth > docker-logs/auth.log
          docker compose logs db > docker-logs/db.log
          docker compose logs phpmyadmin > docker-logs/phpmyadmin.log

      - name: Upload Logs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: container-logs
          path: docker-logs/

      - name: Clean Up Containers
        if: always()
        run: docker compose down --volumes --remove-orphans
