name: phpmyadmin CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  docker-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and Run Docker Compose
        run: docker-compose up -d --build

      - name: Wait for Services to Initialize
        run: sleep 30

      - name: Check Running Containers
        run: docker ps

      - name: Check Backend Health Endpoint
        run: |
          curl --fail http://localhost:8080/health

      - name: Check phpMyAdmin Availability
        run: |
          curl --fail http://localhost:8081 || echo "phpMyAdmin might take extra time to load..."

      - name: Check Docker Networks
        run: docker network ls

      - name: Cleanup Containers
        if: always()
        run: docker-compose down
